# server properties
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: tomcat
    key-password: password


# logging properties
logging:
  level.org.springframework: debug
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %C:%L - %m%n'
  file: logs/app.log

# actuator properties
## To expose all actuator end points
management:
  endpoints.web.exposure.include: '*'
## In order to see the information of the built-in health indicators
  endpoint.health.show-details: always
## To see complete info from target/classes/git.properties
  info.git.mode: full

## info end point properties
info:
  app.name: spring-boot-actuator-practice-examples
  app.description: Spring Boot Actuator Practice Examples
  app.version: 1.0
  java-vendor: ${java.specification.vendor}